import type { DashboardOverview, Product } from "@/types/domain";

export const siteConfig = {
  name: "Smart Commerce",
  description:
    "A marketplace-inspired storefront for daily essentials, home upgrades, beauty picks, fashion basics, and smart household shopping.",
  tagline: "Fresh deals, trusted essentials, and smarter commerce in one place.",
};

export const fallbackProducts: Product[] = [
  {
    id: "fallback-1",
    name: "Premium Basmati Rice 5kg",
    slug: "premium-basmati-rice-5kg",
    sku: "GR-RC-001",
    description:
      "Long-grain aromatic rice selected for family meals, festive biryani, and weekly pantry refills.",
    price: 890,
    compareAtPrice: 980,
    stock: 44,
    reorderPoint: 18,
    rating: 4.7,
    featured: true,
    tags: ["rice", "grocery", "daily-essentials"],
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 286,
      views30d: 4280,
      conversionRate: 6.1,
    },
    category: {
      id: "grocery-essentials",
      name: "Grocery Essentials",
      slug: "grocery-essentials",
    },
  },
  {
    id: "fallback-2",
    name: "Fresh Farm Eggs 12pcs",
    slug: "fresh-farm-eggs-12pcs",
    sku: "GR-EG-002",
    description: "Clean, carefully packed eggs for everyday breakfasts, baking, and healthy family meals.",
    price: 195,
    compareAtPrice: 220,
    stock: 62,
    reorderPoint: 24,
    rating: 4.8,
    featured: true,
    tags: ["eggs", "grocery", "fresh"],
    images: [
      "https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 352,
      views30d: 5140,
      conversionRate: 6.8,
    },
    category: {
      id: "grocery-essentials",
      name: "Grocery Essentials",
      slug: "grocery-essentials",
    },
  },
  {
    id: "fallback-3",
    name: "Cold Pressed Mustard Oil 1L",
    slug: "cold-pressed-mustard-oil-1l",
    sku: "GR-OL-003",
    description: "Rich, punchy mustard oil packed for traditional cooking, curries, and everyday frying.",
    price: 260,
    compareAtPrice: 300,
    stock: 51,
    reorderPoint: 20,
    rating: 4.6,
    featured: true,
    tags: ["oil", "grocery", "cooking"],
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 224,
      views30d: 3680,
      conversionRate: 5.4,
    },
    category: {
      id: "grocery-essentials",
      name: "Grocery Essentials",
      slug: "grocery-essentials",
    },
  },
  {
    id: "fallback-4",
    name: "Family Laundry Detergent 3kg",
    slug: "family-laundry-detergent-3kg",
    sku: "HC-DT-004",
    description: "Deep-clean detergent built for family-size washing loads with long-lasting freshness.",
    price: 640,
    compareAtPrice: 760,
    stock: 31,
    reorderPoint: 14,
    rating: 4.5,
    featured: true,
    tags: ["detergent", "home-care", "laundry"],
    images: [
      "https://images.unsplash.com/photo-1583947582886-f40ec95dd752?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 174,
      views30d: 2940,
      conversionRate: 5.1,
    },
    category: {
      id: "home-care",
      name: "Home Care",
      slug: "home-care",
    },
  },
  {
    id: "fallback-5",
    name: "Citrus Floor Cleaner 2L",
    slug: "citrus-floor-cleaner-2l",
    sku: "HC-FC-005",
    description: "A bright, clean-smelling floor cleaner that keeps tiles and hard surfaces fresh.",
    price: 390,
    compareAtPrice: 450,
    stock: 26,
    reorderPoint: 12,
    rating: 4.4,
    featured: false,
    tags: ["cleaner", "home-care", "floor"],
    images: [
      "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 128,
      views30d: 2140,
      conversionRate: 4.8,
    },
    category: {
      id: "home-care",
      name: "Home Care",
      slug: "home-care",
    },
  },
  {
    id: "fallback-6",
    name: "Herbal Repair Shampoo 650ml",
    slug: "herbal-repair-shampoo-650ml",
    sku: "PC-SH-006",
    description: "Salon-style repair shampoo with herbal extracts for soft, manageable daily hair care.",
    price: 520,
    compareAtPrice: 610,
    stock: 48,
    reorderPoint: 16,
    rating: 4.6,
    featured: true,
    tags: ["shampoo", "beauty", "personal-care"],
    images: [
      "https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 189,
      views30d: 3380,
      conversionRate: 5.6,
    },
    category: {
      id: "personal-care",
      name: "Personal Care",
      slug: "personal-care",
    },
  },
  {
    id: "fallback-7",
    name: "Aloe Vera Face Wash",
    slug: "aloe-vera-face-wash",
    sku: "PC-FW-007",
    description: "Lightweight daily face wash that keeps skin fresh, calm, and clean after long days outside.",
    price: 350,
    compareAtPrice: 420,
    stock: 40,
    reorderPoint: 15,
    rating: 4.5,
    featured: false,
    tags: ["face-wash", "beauty", "personal-care"],
    images: [
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 141,
      views30d: 2490,
      conversionRate: 5.3,
    },
    category: {
      id: "personal-care",
      name: "Personal Care",
      slug: "personal-care",
    },
  },
  {
    id: "fallback-8",
    name: "Stainless Steel Lunch Box",
    slug: "stainless-steel-lunch-box",
    sku: "KD-LB-008",
    description: "Compact insulated lunch box for office meals, school snacks, and everyday carrying convenience.",
    price: 780,
    compareAtPrice: 980,
    stock: 22,
    reorderPoint: 10,
    rating: 4.7,
    featured: false,
    tags: ["lunch-box", "kitchen", "daily-use"],
    images: [
      "https://images.unsplash.com/photo-1520085601670-ee14aa5fa3e8?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 116,
      views30d: 1940,
      conversionRate: 4.9,
    },
    category: {
      id: "kitchen-dining",
      name: "Kitchen & Dining",
      slug: "kitchen-dining",
    },
  },
  {
    id: "fallback-9",
    name: "Non-Stick Fry Pan 28cm",
    slug: "non-stick-fry-pan-28cm",
    sku: "KD-FP-009",
    description: "Everyday fry pan with easy-clean coating for quick breakfasts and weeknight cooking.",
    price: 1450,
    compareAtPrice: 1690,
    stock: 18,
    reorderPoint: 8,
    rating: 4.6,
    featured: true,
    tags: ["cookware", "kitchen", "pan"],
    images: [
      "https://images.unsplash.com/photo-1544025162-d76538925058?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 104,
      views30d: 1860,
      conversionRate: 4.4,
    },
    category: {
      id: "kitchen-dining",
      name: "Kitchen & Dining",
      slug: "kitchen-dining",
    },
  },
  {
    id: "fallback-10",
    name: "FastCharge Power Bank 20000mAh",
    slug: "fastcharge-power-bank-20000mah",
    sku: "EL-PB-010",
    description: "High-capacity fast-charging power bank for heavy phone users, travel days, and load-shedding backup.",
    price: 2190,
    compareAtPrice: 2590,
    stock: 15,
    reorderPoint: 8,
    rating: 4.8,
    featured: true,
    tags: ["power-bank", "electronics", "mobile"],
    images: [
      "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 132,
      views30d: 2680,
      conversionRate: 4.9,
    },
    category: {
      id: "electronics-gadgets",
      name: "Electronics & Gadgets",
      slug: "electronics-gadgets",
    },
  },
  {
    id: "fallback-11",
    name: "Emergency LED Lantern",
    slug: "emergency-led-lantern",
    sku: "EL-LN-011",
    description: "Portable rechargeable lantern built for power cuts, evening errands, and backup home lighting.",
    price: 1280,
    compareAtPrice: 1490,
    stock: 27,
    reorderPoint: 10,
    rating: 4.5,
    featured: false,
    tags: ["lantern", "electronics", "emergency"],
    images: [
      "https://images.unsplash.com/photo-1517999144091-3d9dca6d1e43?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 96,
      views30d: 1540,
      conversionRate: 4.2,
    },
    category: {
      id: "electronics-gadgets",
      name: "Electronics & Gadgets",
      slug: "electronics-gadgets",
    },
  },
  {
    id: "fallback-12",
    name: "Everyday Cotton Panjabi",
    slug: "everyday-cotton-panjabi",
    sku: "FS-PJ-012",
    description: "Light, breathable panjabi for family gatherings, Friday wear, and everyday festive styling.",
    price: 1690,
    compareAtPrice: 1990,
    stock: 21,
    reorderPoint: 9,
    rating: 4.7,
    featured: true,
    tags: ["fashion", "panjabi", "menswear"],
    images: [
      "https://images.unsplash.com/photo-1618886614638-80e3c103d31a?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 111,
      views30d: 2020,
      conversionRate: 4.6,
    },
    category: {
      id: "fashion-lifestyle",
      name: "Fashion & Lifestyle",
      slug: "fashion-lifestyle",
    },
  },
  {
    id: "fallback-13",
    name: "Comfort Slide Sandals",
    slug: "comfort-slide-sandals",
    sku: "FS-SD-013",
    description: "Soft cushioned sandals designed for home, errands, and all-day casual comfort.",
    price: 990,
    compareAtPrice: 1250,
    stock: 36,
    reorderPoint: 14,
    rating: 4.4,
    featured: false,
    tags: ["fashion", "sandals", "footwear"],
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 88,
      views30d: 1700,
      conversionRate: 4.1,
    },
    category: {
      id: "fashion-lifestyle",
      name: "Fashion & Lifestyle",
      slug: "fashion-lifestyle",
    },
  },
  {
    id: "fallback-14",
    name: "Compact Kitchen Blender 1.5L",
    slug: "compact-kitchen-blender-1-5l",
    sku: "KD-BL-014",
    description: "A reliable everyday blender for smoothies, spice pastes, sauces, and quick kitchen prep.",
    price: 2890,
    compareAtPrice: 3390,
    stock: 12,
    reorderPoint: 6,
    rating: 4.6,
    featured: false,
    tags: ["blender", "kitchen", "appliances"],
    images: [
      "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=1200&q=80",
    ],
    metrics: {
      sales30d: 74,
      views30d: 1430,
      conversionRate: 3.9,
    },
    category: {
      id: "kitchen-dining",
      name: "Kitchen & Dining",
      slug: "kitchen-dining",
    },
  },
];

export const fallbackDashboardOverview: DashboardOverview = {
  kpis: [
    { label: "Revenue this week", value: "$18,620", delta: "+12.4%", tone: "success" },
    { label: "Orders", value: "156", delta: "+8.1%", tone: "neutral" },
    { label: "Active products", value: "48", delta: "+6 added", tone: "neutral" },
    { label: "Customers", value: "1,284", delta: "+14.3%", tone: "success" },
  ],
  revenueSeries: [
    { label: "Mon", revenue: 5200, orders: 24 },
    { label: "Tue", revenue: 5650, orders: 27 },
    { label: "Wed", revenue: 6100, orders: 31 },
    { label: "Thu", revenue: 6480, orders: 33 },
    { label: "Fri", revenue: 6920, orders: 35 },
    { label: "Sat", revenue: 7400, orders: 38 },
    { label: "Sun", revenue: 7760, orders: 41 },
  ],
  inventoryAlerts: [
    {
      id: "alert-1",
      name: "FastCharge Power Bank 20000mAh",
      vendorName: "Demo Vendor",
      sku: "EL-PB-010",
      stock: 4,
      reorderPoint: 8,
      threshold: 7,
      urgency: "high",
      recommendedOrderQty: 3,
    },
    {
      id: "alert-2",
      name: "Compact Kitchen Blender 1.5L",
      vendorName: "Demo Vendor",
      sku: "KD-BL-014",
      stock: 0,
      reorderPoint: 6,
      threshold: 7,
      urgency: "critical",
      recommendedOrderQty: 7,
    },
  ],
  topProducts: [
    {
      id: "tp-1",
      name: "Fresh Farm Eggs 12pcs",
      sales30d: 352,
      views30d: 5140,
      conversionRate: 6.8,
      stock: 62,
    },
    {
      id: "tp-2",
      name: "Premium Basmati Rice 5kg",
      sales30d: 286,
      views30d: 4280,
      conversionRate: 6.1,
      stock: 44,
    },
    {
      id: "tp-3",
      name: "Herbal Repair Shampoo 650ml",
      sales30d: 189,
      views30d: 3380,
      conversionRate: 5.6,
      stock: 48,
    },
  ],
  recentOrders: [
    {
      id: "ord-1",
      orderNumber: "ORD-2026-005",
      customerName: "Sadia Karim",
      customerEmail: "sadia@example.com",
      subtotal: 244,
      shippingFee: 20,
      total: 264,
      status: "pending",
      paymentMethod: "cod",
      paymentStatus: "pending",
      items: [],
      createdAt: "2026-04-22T12:00:00.000Z",
    },
    {
      id: "ord-2",
      orderNumber: "ORD-2026-004",
      customerName: "Rifat Hossain",
      customerEmail: "rifat@example.com",
      subtotal: 393,
      shippingFee: 0,
      total: 393,
      status: "delivered",
      paymentMethod: "cod",
      paymentStatus: "paid",
      items: [],
      createdAt: "2026-04-21T12:00:00.000Z",
    },
  ],
  auditActivity: [
    {
      id: "log-1",
      actorEmail: "admin@smartcommerce.local",
      action: "inventory.threshold_adjusted",
      entityType: "product",
      status: "success",
      createdAt: "2026-04-22T14:30:00.000Z",
    },
    {
      id: "log-2",
      actorEmail: "admin@smartcommerce.local",
      action: "analytics.overview_viewed",
      entityType: "dashboard",
      status: "success",
      createdAt: "2026-04-22T09:15:00.000Z",
    },
  ],
};
